### ISSUE TITLE
Inject not a function

### ISSUE THREAD

**Issue by TbirdDuncan** [RStankov/backbone-handlebars#3]
viewClass = _.inject((name || '').split('.'), (function(memo, fragment) {
_.inject is not a function

Thoughts?

EDIT: ANSWER: I think replacing _.inject on line 21 in the postponeRender function with _.reduce fixes this. Not 100% sure, but no errors are given. https://underscorejs.org/#reduce

**Comment by RStankov** [comment]
You are right. Inject was removed from unserscore long ago 😅

In this case a normal reduce will do the trick.

✅ [Fixed](https://github.com/RStankov/backbone-handlebars/commit/93b1dc999d69d04e16068e96cdecb1f2e15a35e6)

**Comment by TbirdDuncan** [comment]
Also I am curious, is models in views just an array identifying how many to
create? Or can it actually be a model?

**Comment by RStankov** [comment]
@TbirdDuncan  I don't understand the question?

**Comment by TbirdDuncan** [comment]
that.renderTemplate({models: [t,t]});
this renders 2 models
however
        that.renderTemplate({models: [t]});
only renders 1, even though t is an array containing multiple objects

**Comment by RStankov** [comment]
```
that.renderTemplate({models: [t]});
```

This should render 1 model.

**Comment by TbirdDuncan** [comment]
I literally just figured out my preferred functionality.
{{views "name of my view" models}}
var models = {models: []}
        //function that pushes objects like this: models.models.push(x),
where x is your object, it can contain models
        that.renderTemplate(models);

this adds an extra call however to the views rendered and hands it
undefined stuff, I cant figure it out...
